# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on: [push]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.20.1

    - name: Lint
      run: make lint

    - name: Test
      run: make test

    - name: Build
      run: make build

    - name: Upload Linux Go build
      uses: actions/upload-artifact@v3
      with:
        name: go-in-tests-linux
        path: go-in-tests-linux

    - name: Upload Mac Go build
      uses: actions/upload-artifact@v3
      with:
        name: go-in-tests-darwin
        path: go-in-tests-darwin

    - name: Upload Win Go build
      uses: actions/upload-artifact@v3
      with:
        name: go-in-tests-windows
        path: go-in-tests-windows
